export const BETTERPERFORMANCEIMG = require('../assets/images/betterPerformance.png')
export const BLURIMG = require('../assets/images/blur.png')
export const BUILDWEALTH = require('../assets/images/buildWealth.jpeg')
export const EXTENSIONIMG = require('../assets/images/extension.jpeg')
export const LINEARBG = require('../assets/images/linearGradient.png')
export const PLANWEDDINGIMG = require('../assets/images/planWedding.jpeg')
export const QTYASSETIMG = require('../assets/images/qualityAssets.png')
export const SUPSELECTIMG = require('../assets/images/superiorSelection.png')